### ISSUE TITLE
Missing variants

### ISSUE THREAD

**Issue by chrislueders** [GBKS/bitcoin-wallet-ui-kit#25]
There are a couple of broken component variants used in the UI kit.
If I find them, I will screenshot and collect them here, we should fix them at some point:

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/120942532/218146139-6540c9cd-70fe-4bda-b228-0da76722f4e9.png">

**Comment by GBKS** [comment]
I fixed a lot of them the past few days, primarily "Basic mobile screen header" instances. Might be nice to create/find a plug-in that lists out problematic instances to easily hunt them down.

An intricate thing is that some list items have sub-components whose main components have been deleted.

Without automating this hunt, I am not sure we can track down all the issues. Will have to look into plugins...

**Comment by GBKS** [comment]
This should be fixed. I wrote a plug-in that analyzes the whole file and lists out these missing ones. Then I went through and fixed them (not pushed to community yet, only in the working file).
