### ISSUE TITLE
Set up button component / Penpot

### ISSUE THREAD

**Issue by GBKS** [GBKS/bitcoin-wallet-ui-kit#30]
Create a button component with all states and properties from the Figma file that is easy to maintain, customize and use.

**Comment by chrislueders** [comment]
i did this already. It's just a bit stupid, that we cant swap the icons easily...

**Comment by GBKS** [comment]
This is pretty much done with current Penpot capabilities. As @chrislueders mentioned, several Figma features are really missing here ([variants](https://help.figma.com/hc/en-us/articles/360056440594-Create-and-use-variants), [properties](https://help.figma.com/hc/en-us/articles/5579474826519-Explore-component-properties), and [instance swapping](https://help.figma.com/hc/en-us/articles/360039150413-Swap-components-and-instances)). Result is that you cannot drag in a general button component into your screen and configure it with a few clicks. Instead, we have lots of button components representing different states and configurations, and you need to drag in the one you need. With icons, you also can't just easily switch out the default one. You have to delete the one in there, and then add the icon you want from the assets library (one of the reasons why icon frames should all have the same size). Much more manual and makes it harder to manage the design system. But that's the best we can do at the moment, and we can re-evaluate as Penpot evolves.

Closing this issue for now.
