### ISSUE TITLE
Set up colors & themes / Penpot

### ISSUE THREAD

**Issue by GBKS** [GBKS/bitcoin-wallet-ui-kit#31]
Find the best way to set up [colors](https://www.bitcoinuikit.com/foundation) and light/dark themes in Penpot for maintenance, customization and usage.

**Comment by chrislueders** [comment]
We did this already. But "themes" arent possible. We just have the both color palettes for light and dark.

**Comment by swedishfrenchpress** [comment]
Colors in the original file "Bitcoin UI Kit (Working)". They're setup with both the "Light" and "Dark"

**Comment by GBKS** [comment]
Even with free Figma it's only possible via plug-ins. Maybe this is something that we ignore for now until the Penpot plug-in system becomes available.

**Comment by GBKS** [comment]
Colors are set up, but we have some issues that could be improved over time.

- There is no easy way to switch themes right now. In Figma, we used a custom plug-in, and they also recently added the (paid) mode feature to allow for theme switching
- The Penpot color picker shows colors in a seemingly random order and does not make the path easily recognizable (you have to hover to see even just the name). The assets sidebar is most usable right now. For the reason, we added sun and moon emoji to the color names

Going to close this issue, as the colors are set up well for the time being.
