### ISSUE TITLE
Navigation component / Penpot

### ISSUE THREAD

**Issue by GBKS** [GBKS/bitcoin-wallet-ui-kit#37]

**Comment by thevladimirkrstic** [comment]
Ready for review. 

Notes: 

- There is no slashed zero Open Type feature available in Penpot, because of that "Balance Amount" is without slashed zero.
- There is no "Button / Free /  Medium" with "Icon / Big" referenced in "Form elements", left it without component for now.

**Comment by GBKS** [comment]
Looking good, thanks for picking this up. I reviewed and fixed a few layout issues. For example, when scaling the top nav bar vertically, the items inside of it did not properly stretch/center. Important to ensure that the component can resize and things still look good. I think it's all fixed now, but Penpot certainly does not make it easy to be sure. Closing this issue as completed for now.
