### ISSUE TITLE
colors: primary colors dark mode

### ISSUE THREAD

**Issue by reez** [GBKS/bitcoin-wallet-ui-kit#6]
Just saw you had a "Dark theme exploration" page in the Figma file, cool!

<img width="343" alt="Screen Shot 2021-06-26 at 3 05 29 PM" src="https://user-images.githubusercontent.com/6657488/123524441-f42a1c80-d68f-11eb-9f7f-0ec89693c926.png">

I know its an exploration, but I went ahead and added the dark mode of the neutrals to WalletUI since they were available.

<img width="726" alt="Screen Shot 2021-06-26 at 3 05 47 PM" src="https://user-images.githubusercontent.com/6657488/123524448-fee4b180-d68f-11eb-88b0-c2d72e68c1e5.png">

**Do you have the dark mode of the primary and accents?**

<img width="757" alt="Screen Shot 2021-06-26 at 3 06 00 PM" src="https://user-images.githubusercontent.com/6657488/123524453-06a45600-d690-11eb-9e0b-02a5d0231df8.png">

I'd love to add them to WalletUI-

**Comment by GBKS** [comment]
Thanks for picking this up. I'll have more for the UI kit in the next weeks and will try to clean up the dark mode. I also want to make it compatible with this Figma plugin called [Lights](https://www.figma.com/community/plugin/780821534053786200/Lights), which allows you to switch screens back and forth between themes. More to come...

**Comment by reez** [comment]
Yeah I thought Lights looked sweet when Jordan or Cash App (I think?) dropped it recently, nice!

**Comment by GBKS** [comment]
I think the dark mode is complete now. You can see the color palette in the "[Colors](https://www.figma.com/file/VB3GQdAnhl8yta44DY3PSV/Bitcoin-Wallet-UI-Kit?node-id=96%3A1834)" page, it's no longer an exploration page, I added dark versions of the secondary colors, and the Lights plugin does the rest. Is there anything else you still need for this?

**Comment by reez** [comment]
yes yes yes! looks good
